### ISSUE TITLE
Problem of removing links 😡

### ISSUE THREAD

**Issue by Q7v** [NilPointer-Software/bdfd-wiki#114]
The problem of removing links should be First message and this is sad because some people put the link in the last message or in the middle of a message and the bot can not delete it and this is very annoying

**Comment by DevSpen** [comment]
The premium [`$messageContains`](https://nilpointer-software.github.io/bdfd-wiki/premium/messageContains.html) callback solves this issue, although it isn't a bug, using command triggers only checks the start of a message not the full contents.
