### ISSUE TITLE
Function Argument Update Bugs

### ISSUE THREAD

**Issue by DevSpen** [NilPointer-Software/bdfd-wiki#116]
# Function Argument Update Bugs
Fair warning: I have no idea what has been fixed yet or not, so feel free to check off anything that has already been fixed <3

If anything is not a bug/invalid give a ~~strikethrough~~.

- [x] `$allowRoleMentions[]`/`$allowUserMentions[]` when used without inputting any userIDs results in the bot not responding.
- [x] `$optOff[]` when used on a function-set that doesn't return any outputs results in a error. [(see example)](https://user-images.githubusercontent.com/69215413/147842650-0164637c-2548-486b-ac08-cc46ecd99db2.png)
- [x] `$textSplit[]` now removes spaces from the <separator> again, although the bug was fixed a while back.
- [x] Unable to leave argument 3 (label) as empty in `$addButton[]` even when there is an emoji set (a feature supporting empty labels when emojis are used was added awhile back).
- [x] `$isBot[]` returns a error if you leave the 1st argument empty.
- [x] ~~If I remember correctly, `$isBot[]` didn't check if the user actually exists, rather it returned false. Now, it requires the first argument to be a snowflake. I could be wrong about this however, but if this was the case, I suggest making it work like the old way~~
- [x] `$async[]` allows the first argument (the async block's name) to be left empty (and `$await[]` doesn't).
- [x] `$removeLinks` doesn't work when used without brackets, as it used to.
- [x] `$toUppercase[]` doesn't work
- [x] `$newTicket[]`'s second argument (message when no ticket) should be emptiable as it used to.
- [x] `$sort[]` trims spaces from the last argument (separator), so if you use `, `  it will be outputted as `,`.
- …I’ll add more as they get reported / found

**Comment by noituri** [comment]
Thanks, that's exactly what we needed <3

**Comment by MineBartekSA** [comment]
> If I remember correctly, $isBot[] didn't check if the user actually exists, rather it returned false. Now, it requires the first argument to be a snowflake. I could be wrong about this however, but if this was the case, I suggest making it work like the old way

The old way also checked if the user existed, so it is written the same way
