### ISSUE TITLE
Why 3.211 3.212 Repeat

### ISSUE THREAD

**Issue by pan783** [NilPointer-Software/bdfd-wiki#118]

**Comment by noituri** [comment]
Hi,
Could you provide more information on the issue?

**Comment by pan783** [comment]
![Screenshot_2022-01-10-18-44-13-51](https://user-images.githubusercontent.com/77907530/148753348-53d28993-89a3-4e49-9027-1880586d45d2.jpg)

**Comment by noituri** [comment]
Thanks for reporting it

**Comment by noituri** [comment]
Fixed in https://github.com/NilPointer-Software/bdfd-wiki/pull/119
