### ISSUE TITLE
Automated Deployments

### ISSUE THREAD

**Issue by DevSpen** [NilPointer-Software/bdfd-wiki#149]
### The Issue
As of right now, deployments to the wiki site have to be manually done.

### Resolution 
It is possible to have CI resolve this issue.\
I'm suggesting that a GitHub action automatically deploys changes when they are pushed.

### Resources
-  https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions#github-pages-deploy
- https://rust-lang.github.io/mdBook/continuous-integration.html
- https://github.com/features/actions

**Comment by MineBartekSA** [comment]
An automatic deployment system using github actions was added (https://github.com/NilPointer-Software/bdfd-wiki/commit/63909329bb4c33e8dbea27c09172a51814b0a880)
Changes to the branch `prerelease` will now be automatically deployed to a nightly subdirectory.
You can view this deployment [here](https://nilpointer-software.github.io/bdfd-wiki/nightly)

**Comment by DevSpen** [comment]
That's awesome! :clap:
