### ISSUE TITLE
Loading issue infinitely

### ISSUE THREAD

**Issue by zLancx** [NilPointer-Software/bdfd-wiki#372]
Loading infinitely 

Uploading Screenrecording_20240104_055400.mp4…

https://github.com/NilPointer-Software/bdfd-wiki/assets/89555026/b840df3f-0082-44e7-894a-a185dd2e316c

**Comment by zLancx** [comment]
Please fix this issue ive been exhausted because of this and i started to panic.

**Comment by MineBartekSA** [comment]
If you are still having this issue, please contact support on our [official Discord server](https://discord.com/servers/bot-designer-for-discord-official-server-566363823137882154)
