### ISSUE TITLE
Feature Request: Webhook Improvements

### ISSUE THREAD

**Issue by DevSpen** [NilPointer-Software/bdfd-wiki#93]
# Webhook Feature Request
With the introduction of [webhook support](https://discord.com/channels/566363823137882154/566364581522440232/873520094565773313) on 07-08-2021, this feature request presumes that the concurrent webhook system is editable and open to modifications. This request is based on frequent feedback I've noticed, and solutions I have thought of. 

This issue is split into two sections; as there are two separate feature requests.

## Webhook Embeds
The current system of sending embeds for webhooks is fine as-is, however; it's very limiting. The reason for this is common embed properties are missing (e.g. authors, thumbnails, images, etc). The second issue regarding webhook embeds is that there are multiple different functions that could possibly be condensed into one or two functions. Here's two ideas I had in mind to combat this issue:
1.`$webhookEmbed[webhookURL;content;title;titleURL;description;color;author;authorIcon;footer;footerIcon;thumbnail;image;addTimestamp (yes/no)]` - Sends a embedded message as a webhook. Uneeded fields can be left empty.
2. `$webhookEmbed[webhookURL;embedJSON]` - Sends a embedded message as a webhook from a [embed raw JSON](https://birdie0.github.io/discord-webhooks-guide/index.html). 

- The benefit of *1* would be it supports most embed properties.
- The benefit of *2* would be it allows for alot of customization, although the logistics of the function would be difficult.

## Deleting Webhooks
Another request in mind is a way to delete existing webhooks, `$webhookDelete[]`.

###  Avoiding Breaking Changes
To avoid breaking changes on the webhook embed behalf, the solution would be to keep existing webhook embed functions; and simply adding a option to use the more advanced *(and customizable)*  `$webhookEmbed[]` version.

### Epilogue
Thanks for reading this issue and considering it, it's definitely open for conversation :)

**Comment by Noituri** [comment]
>1.$webhookEmbed[webhookURL;content;title;titleURL;description;color;author;authorIcon;footer;footerIcon;thumbnail;image;addTimestamp (yes/no)]

I like this one more. It's more BDScript-like.

**Comment by DevSpen** [comment]
> > 1.$webhookEmbed[webhookURL;content;title;titleURL;description;color;author;authorIcon;footer;footerIcon;thumbnail;image;addTimestamp (yes/no)]
> 
> I like this one more. It's more BDScript-like.

Yes, best to keep it as user friendly as possible!

**Comment by Noituri** [comment]
Added
